# Generated by Django 5.2.8 on 2025-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Conta"),
                ),
                (
                    "saldo",
                    models.FloatField(default=0.0, verbose_name="Saldo da Conta"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CREDITO", "Crédito"),
                            ("CREDITO/DEBITO", "Crédito/Débito"),
                            ("DEBITO", "Débito"),
                        ],
                        default="",
                        max_length=14,
                        verbose_name="Tipo da Conta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Financeira",
                "verbose_name_plural": "Contas Financeiras",
            },
        ),
    ]
