# Generated by Django 5.2.8 on 2025-12-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Conta"),
                ),
                ("saldo", models.FloatField(verbose_name="Saldo da Conta")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CREDITO", "Crédito"),
                            ("CREDITO/DEBITO", "Crédito/Débito"),
                            ("DEBITO", "Débito"),
                        ],
                        max_length=14,
                        verbose_name="Tipo da Conta",
                    ),
                ),
            ],
        ),
    ]
