# Generated by Django 6.0.1 on 2026-01-21 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contafinanceira",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contas_financeiras",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário da Conta",
            ),
        ),
    ]
