# Generated by Django 5.2.7 on 2025-12-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contafinanceira',
            name='tipo',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('CREDITO_DEBITO', 'Crédito/Débito'), ('DEBITO', 'Débito')], default='', max_length=14, verbose_name='Tipo da Conta'),
        ),
    ]
