# Generated by Django 5.2.7 on 2026-01-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_contafinanceira_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contafinanceira',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
