# Generated by Django 5.2.8 on 2025-12-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marcador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=70, verbose_name="Nome")),
                ("cor", models.CharField(max_length=7, verbose_name="Cor")),
            ],
        ),
    ]
