# Generated by Django 5.2.7 on 2026-01-26 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marcador',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcadores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marcador',
            name='cor',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='marcador',
            name='nome',
            field=models.CharField(max_length=70),
        ),
    ]
