# Generated by Django 6.0.1 on 2026-01-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("alimentacao", "Alimentação"),
                            ("educacao", "Educação"),
                            ("entretenimento", "Entretenimento"),
                            ("financeiro", "Financeiro"),
                            ("imprevistos", "Imprevistos"),
                            ("saude", "Saúde"),
                            ("trabalho", "Trabalho"),
                            ("transporte", "Transporte"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("realizada", "Realizada"), ("pendente", "Pendente")],
                        default="realizada",
                        max_length=50,
                        verbose_name="Estado da Transação",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")],
                        default="despesa",
                        max_length=50,
                        verbose_name="Tipo da Transação",
                    ),
                ),
                ("data_hora", models.DateTimeField(verbose_name="Data")),
                (
                    "conta_financeira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes",
                        to="contas.contafinanceira",
                        verbose_name="Conta Financeira",
                    ),
                ),
                (
                    "marcadores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transacoes",
                        to="categoria.marcador",
                        verbose_name="Marcadores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
            },
        ),
    ]
