# Generated by Django 5.2.7 on 2025-12-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='id_conta_financeira',
            new_name='conta_financeira',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='id_marcadores',
            new_name='marcadores',
        ),
    ]
