# Generated by Django 5.2.7 on 2025-12-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_rename_id_conta_financeira_transacao_conta_financeira_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='data',
            new_name='data_hora',
        ),
    ]
