# Generated by Django 5.2.7 on 2025-12-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_rename_data_transacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
