# Generated by Django 5.2.7 on 2025-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0004_alter_transacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
