# Generated by Django 5.2.7 on 2025-12-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0005_alter_transacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='estado',
            field=models.CharField(choices=[('realizada', 'Realizada'), ('pendente', 'Pendente')], default='realizada', max_length=50, verbose_name='Estado da Transação'),
        ),
    ]
