# Generated by Django 5.2.7 on 2026-01-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0006_alter_transacao_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
