spring.application.name=na-ponta-do-lapis

# Define o contexto da aplicação para /api
server.servlet.context-path=/api

# Altera o endpoint do swagger
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

# Configurações de Data e Fuso Horário
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo
spring.jackson.deserialization.adjust-dates-to-context-time-zone=true

# Inicialização de banco de dados
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Libera Requisição atraves do codespace (e essencial para o Nginx em produção)
server.forward-headers-strategy=framework

# Cloudinary config (Modificado para usar variáveis de ambiente como prioridade)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:chave-nao-encontrada}
cloudinary.api_key=${CLOUDINARY_API_KEY:chave-nao-encontrada}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:chave-nao-encontrada}

# Gemini config
gemini.api.key=${GEMINI_API_KEY:chave-nao-encontrada}

# JWT config
jwt.secret=${JWT_SECRET:chave-nao-encontrada}
jwt.expire-days=${JWT_EXPIRE_DAYS:1}
jwt.expire-hours=${JWT_EXPIRE_HOURS:1}
jwt.expire-minutes=${JWT_EXPIRE_MINUTES:5}
jwt.expiration-refresh-days=${JWT_EXPIRE_REFRESH_DAYS:7}